e of %d\n",a);    
    printf("5 X 1 = %d\n",a+1);
    printf("6 X 2 = %d\n",a*2);
    printf("6 X 3 = %d\n",a*3);
    printf("6 X 4 = %d\n",a*4);
    printf("6 X 5 = %d\n",a*5);
    printf("6 X 6 = %d\n",a*6);
    printf("6 X 7 = %d\n",a*7);
    printf("6 X 8 = %d\n",a*8);
    printf("6 X 9 = %d\n",a*9);
    printf("6 X 10 = %d\n",a*10);